import Link from 'next/link'
import { Brain, BookOpen, FileText, TrendingUp, CheckCircle, ArrowRight, Zap, Users, Award } from 'lucide-react'

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-white">
      {/* Header */}
      <header className="sticky top-0 z-50 bg-white/90 backdrop-blur-md border-b border-slate-100">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 bg-indigo-600 rounded-lg flex items-center justify-center">
              <Zap className="w-5 h-5 text-white" />
            </div>
            <span className="text-xl font-bold text-slate-900">StudyAce</span>
          </div>
          <nav className="hidden md:flex items-center gap-8">
            <a href="#features" className="text-sm text-slate-600 hover:text-slate-900 transition-colors">Features</a>
            <a href="#how-it-works" className="text-sm text-slate-600 hover:text-slate-900 transition-colors">How it Works</a>
            <a href="#pricing" className="text-sm text-slate-600 hover:text-slate-900 transition-colors">Pricing</a>
          </nav>
          <div className="flex items-center gap-3">
            <Link href="/login" className="text-sm text-slate-600 hover:text-slate-900 font-medium transition-colors">
              Sign in
            </Link>
            <Link
              href="/signup"
              className="text-sm bg-indigo-600 hover:bg-indigo-700 text-white font-medium px-4 py-2 rounded-lg transition-colors"
            >
              Get Started Free
            </Link>
          </div>
        </div>
      </header>

      {/* Hero */}
      <section className="pt-20 pb-24 px-4 sm:px-6">
        <div className="max-w-4xl mx-auto text-center">
          <div className="inline-flex items-center gap-2 bg-indigo-50 text-indigo-700 text-sm font-medium px-3 py-1.5 rounded-full mb-6">
            <Brain className="w-4 h-4" />
            AI-Powered CBSE Preparation
          </div>
          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold text-slate-900 leading-tight mb-6">
            Ace Your CBSE Exams with{' '}
            <span className="text-indigo-600">AI-Powered</span> Practice
          </h1>
          <p className="text-lg sm:text-xl text-slate-600 max-w-2xl mx-auto mb-10 leading-relaxed">
            Personalised practice sessions, previous year style questions, and sample papers for
            Class 9-12 Science & Maths — all powered by AI. Study smarter, not harder.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <Link
              href="/signup"
              className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 text-white font-semibold px-6 py-3.5 rounded-xl transition-colors text-base"
            >
              Start Practising Free
              <ArrowRight className="w-5 h-5" />
            </Link>
            <Link
              href="#how-it-works"
              className="flex items-center gap-2 border border-slate-200 hover:border-slate-300 text-slate-700 font-medium px-6 py-3.5 rounded-xl transition-colors text-base"
            >
              See How It Works
            </Link>
          </div>
          {/* Social proof */}
          <div className="mt-12 flex flex-wrap items-center justify-center gap-8 text-sm text-slate-500">
            <div className="flex items-center gap-2">
              <Users className="w-4 h-4 text-indigo-500" />
              <span>Built for CBSE students</span>
            </div>
            <div className="flex items-center gap-2">
              <BookOpen className="w-4 h-4 text-indigo-500" />
              <span>Class 9–12 covered</span>
            </div>
            <div className="flex items-center gap-2">
              <Brain className="w-4 h-4 text-indigo-500" />
              <span>Powered by Claude AI</span>
            </div>
          </div>
        </div>
      </section>

      {/* Features */}
      <section id="features" className="py-20 bg-slate-50 px-4 sm:px-6">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-14">
            <h2 className="text-3xl font-bold text-slate-900 mb-4">Everything You Need to Score High</h2>
            <p className="text-slate-600 text-lg max-w-2xl mx-auto">
              From chapter-wise practice to full sample papers — we cover your entire CBSE syllabus.
            </p>
          </div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {[
              {
                icon: Brain,
                color: 'bg-indigo-100 text-indigo-600',
                title: 'AI-Generated Questions',
                desc: 'Fresh, unique questions generated by Claude AI for every practice session — no repetition.',
              },
              {
                icon: BookOpen,
                color: 'bg-emerald-100 text-emerald-600',
                title: 'Complete CBSE Syllabus',
                desc: 'All chapters for Science & Maths, Class 9–12. Biology, Physics, Chemistry — fully covered.',
              },
              {
                icon: FileText,
                color: 'bg-amber-100 text-amber-600',
                title: 'Previous Year Style Papers',
                desc: 'Practice with questions modelled after CBSE board exam patterns from recent years.',
              },
              {
                icon: TrendingUp,
                color: 'bg-rose-100 text-rose-600',
                title: 'Track Your Progress',
                desc: 'See your scores, time taken, and improvement across chapters and subjects.',
              },
            ].map((feature) => (
              <div key={feature.title} className="bg-white rounded-2xl p-6 shadow-sm border border-slate-100">
                <div className={`w-12 h-12 rounded-xl flex items-center justify-center mb-4 ${feature.color}`}>
                  <feature.icon className="w-6 h-6" />
                </div>
                <h3 className="font-semibold text-slate-900 mb-2">{feature.title}</h3>
                <p className="text-slate-600 text-sm leading-relaxed">{feature.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How it Works */}
      <section id="how-it-works" className="py-20 px-4 sm:px-6">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-14">
            <h2 className="text-3xl font-bold text-slate-900 mb-4">Get Started in 3 Simple Steps</h2>
            <p className="text-slate-600 text-lg">No setup required. Just sign up and start practising.</p>
          </div>
          <div className="grid sm:grid-cols-3 gap-8">
            {[
              {
                step: '01',
                title: 'Sign Up & Choose Your Class',
                desc: 'Create a free account and select your class (9–12) and subjects.',
              },
              {
                step: '02',
                title: 'Select a Chapter & Mode',
                desc: 'Pick any chapter from your syllabus. Choose Quick Practice, Chapter Test, or Previous Year style.',
              },
              {
                step: '03',
                title: 'Practice & Improve',
                desc: 'Answer AI-generated questions, get instant feedback, and track your progress.',
              },
            ].map((item) => (
              <div key={item.step} className="text-center">
                <div className="w-14 h-14 bg-indigo-600 text-white rounded-2xl flex items-center justify-center text-xl font-bold mx-auto mb-4">
                  {item.step}
                </div>
                <h3 className="font-semibold text-slate-900 mb-2">{item.title}</h3>
                <p className="text-slate-600 text-sm leading-relaxed">{item.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="py-20 bg-slate-50 px-4 sm:px-6">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-14">
            <h2 className="text-3xl font-bold text-slate-900 mb-4">Simple, Affordable Pricing</h2>
            <p className="text-slate-600 text-lg">
              Start free — no credit card required. Upgrade when you&apos;re ready.
            </p>
          </div>
          <div className="grid sm:grid-cols-3 gap-6">
            {/* Free */}
            <div className="bg-white rounded-2xl p-6 border border-slate-200 shadow-sm">
              <h3 className="font-bold text-slate-900 text-lg mb-1">Free</h3>
              <div className="text-3xl font-bold text-slate-900 mb-4">₹0</div>
              <ul className="space-y-3 mb-6">
                {['3 practice sessions', 'All subjects & chapters', 'AI-generated questions', 'Score & feedback'].map((f) => (
                  <li key={f} className="flex items-center gap-2 text-sm text-slate-600">
                    <CheckCircle className="w-4 h-4 text-emerald-500 flex-shrink-0" />
                    {f}
                  </li>
                ))}
              </ul>
              <Link href="/signup" className="block w-full text-center border border-indigo-600 text-indigo-600 hover:bg-indigo-50 font-medium py-2.5 rounded-lg transition-colors text-sm">
                Get Started Free
              </Link>
            </div>
            {/* Monthly */}
            <div className="bg-indigo-600 rounded-2xl p-6 shadow-lg relative">
              <div className="absolute -top-3 left-1/2 -translate-x-1/2 bg-amber-400 text-slate-900 text-xs font-bold px-3 py-1 rounded-full">
                MOST POPULAR
              </div>
              <h3 className="font-bold text-white text-lg mb-1">Monthly</h3>
              <div className="text-3xl font-bold text-white mb-4">₹99<span className="text-lg font-normal text-indigo-200">/mo</span></div>
              <ul className="space-y-3 mb-6">
                {['Unlimited practice sessions', 'All subjects & chapters', 'Previous year questions', 'Sample papers', 'Progress tracking', 'Priority AI generation'].map((f) => (
                  <li key={f} className="flex items-center gap-2 text-sm text-indigo-100">
                    <CheckCircle className="w-4 h-4 text-indigo-300 flex-shrink-0" />
                    {f}
                  </li>
                ))}
              </ul>
              <Link href="/signup" className="block w-full text-center bg-white text-indigo-600 hover:bg-indigo-50 font-semibold py-2.5 rounded-lg transition-colors text-sm">
                Start for ₹99/month
              </Link>
            </div>
            {/* Annual */}
            <div className="bg-white rounded-2xl p-6 border border-slate-200 shadow-sm">
              <h3 className="font-bold text-slate-900 text-lg mb-1">Annual</h3>
              <div className="text-3xl font-bold text-slate-900 mb-1">₹799<span className="text-lg font-normal text-slate-500">/yr</span></div>
              <p className="text-xs text-emerald-600 font-medium mb-4">Save 33% vs monthly</p>
              <ul className="space-y-3 mb-6">
                {['Everything in Monthly', 'Detailed analytics', 'Performance reports', 'Exam strategy guides', 'Priority support'].map((f) => (
                  <li key={f} className="flex items-center gap-2 text-sm text-slate-600">
                    <CheckCircle className="w-4 h-4 text-emerald-500 flex-shrink-0" />
                    {f}
                  </li>
                ))}
              </ul>
              <Link href="/signup" className="block w-full text-center border border-indigo-600 text-indigo-600 hover:bg-indigo-50 font-medium py-2.5 rounded-lg transition-colors text-sm">
                Get Annual Plan
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Banner */}
      <section className="py-20 px-4 sm:px-6">
        <div className="max-w-3xl mx-auto text-center">
          <Award className="w-14 h-14 text-indigo-600 mx-auto mb-6" />
          <h2 className="text-3xl font-bold text-slate-900 mb-4">
            Ready to Score Higher in Your CBSE Exams?
          </h2>
          <p className="text-slate-600 text-lg mb-8">
            Join students who are already practising smarter with StudyAce.
          </p>
          <Link
            href="/signup"
            className="inline-flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 text-white font-semibold px-8 py-4 rounded-xl transition-colors text-base"
          >
            Start Practising Free — No Card Required
            <ArrowRight className="w-5 h-5" />
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-slate-100 py-8 px-4 sm:px-6">
        <div className="max-w-6xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <div className="w-7 h-7 bg-indigo-600 rounded-lg flex items-center justify-center">
              <Zap className="w-4 h-4 text-white" />
            </div>
            <span className="font-semibold text-slate-900">StudyAce</span>
          </div>
          <p className="text-sm text-slate-500">© 2025 StudyAce. CBSE Class 9-12 AI Practice Platform.</p>
          <div className="flex gap-4 text-sm text-slate-500">
            <a href="#" className="hover:text-slate-900 transition-colors">Privacy</a>
            <a href="#" className="hover:text-slate-900 transition-colors">Terms</a>
          </div>
        </div>
      </footer>
    </div>
  )
}
